# Setup
title: 브루스의 블로그
tagline: 게임 개발 블로그
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-B1PRQGKYBL

# Specify the author for blog posts
author:
  name: 이종원
  url: https://github.com/Bruce0203
  email: Bruce0203@gmail.com

# Custom vars
version: 3.0.0
